const now = new Date().toISOString().slice(0, 19).replace("T", " ");

module.exports = {
  users: [
    {
      id: 1,
      name: "Admin Microfun",
      email: "admin@microfun.com",
      password: "Password123!",
      role: "admin",
      created_at: now,
      updated_at: now,
    },
    {
      id: 2,
      name: "Mentor Demo",
      email: "mentor@microfun.com",
      password: "Password123!",
      role: "mentor",
      created_at: now,
      updated_at: now,
    },
    {
      id: 3,
      name: "Owner Demo",
      email: "umkm@microfun.com",
      password: "Password123!",
      role: "umkm_owner",
      created_at: now,
      updated_at: now,
    },
    {
      id: 4,
      name: "Funder Demo",
      email: "funder@microfun.com",
      password: "Password123!",
      role: "funder",
      created_at: now,
      updated_at: now,
    },
  ],
  mentors: [
    {
      id: 1,
      user_id: 2,
      current_job: "Business Consultant",
      experience: "10 years",
      about: "Mentor untuk UMKM",
      reputation_score: 4.8,
      verified: 1,
      created_at: now,
      updated_at: now,
    },
  ],
  mentor_skills: [
    { id: 1, mentor_id: 1, skill: "Marketing", created_at: now, updated_at: now },
    { id: 2, mentor_id: 1, skill: "Finance", created_at: now, updated_at: now },
  ],
  umkm_owners: [
    {
      id: 1,
      user_id: 3,
      nik: "317xxxxxxxxxxxxx",
      npwp: "12.345.678.9-000.000",
      verified: 1,
      created_at: now,
      updated_at: now,
    },
  ],
  umkm_business: [
    {
      id: 1,
      owner_id: 1,
      name: "Kopi Nusantara",
      category: "kuliner",
      description: "UMKM kopi lokal",
      location: "Jakarta",
      verified: 1,
      created_at: now,
      updated_at: now,
    },
  ],
  mentor_sessions: [
    {
      id: 1,
      umkm_owner: 1,
      mentor_id: 1,
      topic: "Strategi Penjualan",
      scheduled_at: now,
      duration_minutes: 90,
      status: "done",
      rating: 5,
      created_at: now,
      updated_at: now,
    },
  ],
  mentor_hours_log: [
    {
      id: 1,
      mentor_id: 1,
      session_id: 1,
      hours_contributed: 2,
      earned_points: 20,
      star: 5,
      created_at: now,
      updated_at: now,
    },
  ],
  funders: [
    {
      id: 1,
      user_id: 4,
      organization_name: "PT Dana UMKM",
      verified: 1,
      created_at: now,
      updated_at: now,
    },
  ],
  fundings: [
    {
      id: 1,
      funder_id: 1,
      business_id: 1,
      amount: 10000000,
      description: "Pendanaan tahap awal",
      status: "approved",
      created_at: now,
      updated_at: now,
    },
  ],
  forums: [
    { id: 1, title: "Forum UMKM", description: "Diskusi UMKM", created_at: now, updated_at: now },
  ],
  posts: [
    {
      id: 1,
      forum_id: 1,
      posted_by: 3,
      title: "Tips meningkatkan omzet",
      body: "Mulai dari validasi pelanggan.",
      status: "published",
      created_at: now,
      updated_at: now,
    },
  ],
  post_likes: [{ id: 1, post_id: 1, user_id: 2, created_at: now }],
  post_tags: [
    { id: 1, post_id: 1, tag: "UMKM", created_at: now, updated_at: now },
    { id: 2, post_id: 1, tag: "Marketing", created_at: now, updated_at: now },
  ],
  comments: [
    { id: 1, post_id: 1, user_id: 2, body: "Konten bagus.", created_at: now, updated_at: now },
  ],
  comment_replies: [
    { id: 1, comment_id: 1, user_id: 3, body: "Terima kasih.", created_at: now, updated_at: now },
  ],
  pictures: [
    {
      id: 1,
      related_id: 1,
      type: "umkm_business",
      caption: "Logo bisnis",
      filepath: "uploads/logo-kopi.png",
      mime_type: "image/png",
      alt_text: "Logo Kopi Nusantara",
      created_at: now,
      updated_at: now,
    },
  ],
  user_documents: [
    {
      id: 1,
      user_id: 3,
      related_type: "umkm_owner",
      document_type: "ktp",
      file_path: "documents/owner-ktp.pdf",
      status: "approved",
      notes: "Valid",
      created_at: now,
      updated_at: now,
    },
  ],
  verification_logs: [
    {
      id: 1,
      verified_by: 1,
      verified_entity_type: "umkm_owner",
      verified_entity_id: 1,
      status: "approved",
      notes: "Sudah diverifikasi",
      created_at: now,
    },
  ],
};
